spring.application.name=selfit
logging.level.org.apache.coyote.http11=trace

#db ?? ??
spring.datasource.url=jdbc:mysql://localhost:3306/selfit?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=0630
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#jpa ??
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

#jwt ??
jwt.secret=4b67208d78e30be0c0e21a73597e256d356d33bc23eb56aefe5805ce10877a5664bd0a6696b96acedb6acaf76f3c5d6afbdfe74f21276d1b0b6cab4e9a371b145cadf205220cf37bfda2e9b534694b7c4857e59ba1a2f7169c38d80a4cc90dcf1caae6f50e6c6998fa075b1ad5d498b555d13c9fcf5bc9e15e11a03b0f38f4fb9d4569a0daf99153fcf2003454e994babf222c693904310bf4c002eb45b80105d9f148dcdcac0f01e5387bf1873f90805b67c86bdc33aa9948698efbf23144b91ed6f2fca120898fcd0216c432dfeb8430c66f6e42492eae6de0a53a03e1d7d8b4a45ef5d8981902358edefca4bf6ed4318f37105687e55a7e1626610087d4c5
jwt.access-expiration=900000
jwt.refresh-expiration=604800000

app.frontend.url=http://localhost:3000
spring.profiles.active=dev

file.upload-dir=C:/Users/deukr/Capstone/Selfit-Server/Image

# 1. ?? ?? ?? ?? ??? (?: 10MB)
spring.servlet.multipart.max-file-size=20MB

# 2. ? ?? ??? ??? ?? ?? ?? ?? ??? (?? 4???? ???? 100MB)
spring.servlet.multipart.max-request-size=100MB

# 3. Tomcat? Swallow ?? ?? ??? (??: ? ??? ??? ??)
# ???? 2MB???. ?? ???? ?? ???? ?? ?????.
server.tomcat.max-swallow-size=100MB


# OAuth2 Client Registration for Kakao
spring.security.oauth2.client.registration.kakao.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.kakao.client-secret=YOUR_CLIENT_SECRET
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/oauth2/login/{registrationId}
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.scope=profile,account_email

# OAuth2 Provider Settings for Kakao
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id
